language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade . -r dev-requirements.txt
  - pip freeze
script:
  - pytest
deploy:
  provider: pypi
  user: "__token__"
  # password: set by TravisCI's environment variable PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    # Only deploy on tagged commits instead of the default of only doing it to
    # the master branch. A tag does not belong specifically to a branch, so
    # without this it would fail to deploy for tags.
    tags: true
